### ISSUE TITLE
Custom tags for EC2 instances and other AWS resources

### ISSUE THREAD

**Issue by axelfontaine** [boxfuse/boxfuse-issues#100]
The proposed syntax for this would be `-tags.abc=def` (multiple tags allowed) which in this case would add the `abc` tag with value `def` to all AWS resources created by Boxfuse, in addition to the existing auto-created tags.

**Comment by anders-holmberg-baath** [comment]
This would be a very nice feature in a current use case that I have.
Using Infinispan/JGroups for cache clustering and tag matching in `AWS_PING` (https://github.com/meltmedia/jgroups-aws) it would be possible to control replication of the instances to be shut down to the newly started instances by matching on the `boxfuse:app` tag and then a manually updated tag (one that can remain the same in case of backward compatibility or be manually bumped otherwise).
The newly started instances could stall by a custom health check that would not return 200 OK until the cache is balanced.
It is already possible to achieve this by versioning convention and using the filter matching instead of tag matching, but it is quite a lot more complicated.
The tagging option would need to be added to the `run` command in order for this case to work.

**Comment by jebl01** [comment]
+1

**Comment by axelfontaine** [comment]
This is now officially supported: https://boxfuse.com/blog/tags
