### ISSUE TITLE
Unable to connect via DNS from another AWS instance in same region when using Load Balanced (ELB) application.

### ISSUE THREAD

**Issue by aweigold** [boxfuse/boxfuse-issues#116]
For reference, our boxfuse account is under: trustedchoicedev@gmail.com

Per the docs, we have configured a DNS CNAME record for our application as stated here: https://boxfuse.com/docs/domains

This works fine when connecting from outside of AWS.  However when trying to connect from another EC2 (non-boxfuse managed) instance, we are getting connection timeouts due to not being able to route to the boxfuse generated hostname.

I am able to establish a connection by going directly to the currently assigned IP directly, however that IP changes every time we deploy as this is a ELB application.

Is this a problem with security group settings on the boxfuse side?  Or is there something we need to change in our network config to allow routing?

**Comment by axelfontaine** [comment]
Hmmm I don't have an immediate answer, but let's proceed through elimination.

As you are able to access your app via your domain from outside EC2 we can assume that:
- your CNAME as well as the underlying boxfuse.io DNS records are correct
- the app is up and running
- the security group of the app allows incoming connections

Since you are able to access your instances behind the ELB via their IP we can additionally assume that:
- packets can be routed from your non-Boxfuse instance to your Boxfuse app

What this then leaves is your non-Boxfuse instance not resolving domains correctly (DNS configuration or caching issue? Try purging it for the latter.). So let's rule out a few more things:
- Are you able to access your app via the ELB DNS name (*.elb.amazonaws.com)?
- Are you able to access your app via the boxfuse.io DNS name?
- Do you have any custom security group configured that may be causing issues on the ELB side?
- Do you have any custom security group configured that may be causing issues on the non-Boxfuse instance side?
- Do you have a firewall on your non-Boxfuse instance that may be causing issues?

**Comment by aweigold** [comment]
- Are you able to access your app via the ELB DNS name (*.elb.amazonaws.com)?
  - There is a connection timeout on the ELB DNS name as well, and it is resolving to the same IP as the boxfuse.io DNS name.
- Are you able to access your app via the boxfuse.io DNS name?
  - No, the DNS is resolving to an IP, but no connection can be made.
- Do you have any custom security group configured that may be causing issues on the ELB side?
  - The security group is set to allow all connections from the security group the non-Boxfuse instance is in.  The security group also allows all connections for the http port.
- Do you have any custom security group configured that may be causing issues on the non-Boxfuse instance side?
  - All outbound requests are allowed in it's security group.
- Do you have a firewall on your non-Boxfuse instance that may be causing issues?
  - No firewall is configured, and confirmed that outbound requests can be made.

Given that the boxfuse.io DNS name points to the same place as the ELB DNS name, I think it's safe to assume that there is *something* within the AWS config on our side.  I didn't know if there was some routing going through Boxfuse instances/resources.  I will keep digging in on my side, but any further ideas are appreciated.

If I find a resolution I'll post a comment.  Given that I'm running on relatively defaulted configs, it may be useful for others to find out how to enable this.

**Comment by aweigold** [comment]
Found the issue.  It is not enough to allow access to the non-Boxfuse instance's security group in the ELB security group, as you end up getting routed outside of the subnet when using the ELB DNS entry.  To fix this, add the Elastic IP of the non-Boxfuse instance to the security group.
