### ISSUE TITLE
NewRelic Java agent breaks Spring webapps compiled javac -parameters

### ISSUE THREAD

**Issue by emilburzo** [boxfuse/boxfuse-issues#164]
Hey,

The latest `newrelic-java` component available with boxfuse (3.35.2) breaks Spring and JAX-RS applications compiled with the Java 8 flag `javac -parameters`.

The issue causes the application to throw a `java.lang.reflect.MalformedParametersException` exception. ([see testcase](https://github.com/komoot/boxfuse-sample-java-springboot-hello))

This is a known issue, [fixed in version 3.36.0](https://docs.newrelic.com/docs/release-notes/agent-release-notes/java-release-notes/java-agent-3360).

Researching this issue, I've noticed NewRelic has an [established release agent version](https://docs.newrelic.com/docs/agents/manage-apm-agents/maintenance/agent-established-releases#java), 3.34.0 currently, which also fixes the issue.

I'm not sure what would make more sense:

* stick to the established agent release
* having the latest agent release

Thanks!

**Comment by axelfontaine** [comment]
Thanks for letting us know!

We decided to avoid the issue altogether by letting the Boxfuse Client download New Relic agent releases directly from their download website, instead of caching them in the Boxfuse Inventory.

Simply update your Boxfuse Client to 1.26.3.1302 with `boxfuse -u` and you'll automatically have access to any New Relic agent release you want, now and in the future.
