### ISSUE TITLE
Spring Boot 2.0 support

### ISSUE THREAD

**Issue by binkley** [boxfuse/boxfuse-issues#174]
While moving to Spring Boot 2.0.0.M1, I noticed boxfuse did not automatically see that the healthcheck endpoint moved:

- Boot 1.x -- `/health`
- Boot 2.x -- `/application/health`

I tried the `-Dhealthcheck.path=/application/health` flag when running `mvn boxfuse:run ...` as suggested in the documentation, but the sysprop seemed to be ignored.  So perhaps I'm doing it wrong.

- Should boxfuse use the newer path for healthcheck in Boot 2.x?  (If so, this is a defect, I suppose)
- How can I get this working for now?
- The documentation could be more clear around this configuration.  For example, I found interesting bits in the Spring Boot docs about boxfuse that I didn't find mentioned in Boxfuse's own docs (https://docs.spring.io/spring-boot/docs/current/reference/html/cloud-deployment.html#cloud-deployment-boxfuse)

**Comment by axelfontaine** [comment]
Thanks for letting us know. We haven't started reviewing the changes made in Spring Boot 2.0 yet (GA is not planned until Q4 2017). Until we do so, you can indeed override the healthcheck path by setting a property. As you can see in the docs (https://boxfuse.com/docs/maven/run) the property is prefixed with `boxfuse.` in order to avoid collisions with other plugins. So in your case this should be `-Dboxfuse.healthcheck.path=/application/health`. Note that if you come across other differences please post them here too, so we can make sure we account for them when implementing our Spring Boot 2.0 support.

In the issue you referenced you mentioned Boxfuse not picking up the artifact with a qualifier. It is correct that by default Boxfuse only picks up the main artifact of the build. You can however override this by specifying the artifact you want in the `boxfuse.payload` property: https://boxfuse.com/docs/maven/run#payload

Which bits in the Spring docs are you missing in our docs?

**Comment by binkley** [comment]
Cool.  Setting `boxfuse.healthcheck.path` did the trick, thanks.

I did not test setting `boxfuse.payload` -- I eliminated the need for a renamed jar (for now) by disabling a _different_ maven plugin which had been conflicting with Spring Boot.  I'll look at that later and let you know.

**Comment by adamzr** [comment]
I'm having the same issue and I should note that Spring Boot 2 is already GA now. If I use a boxfuse.conf file what should the property name be that I need to set?

**Comment by axelfontaine** [comment]
@adamzr It's `healthcheck.path` . See the second column: https://boxfuse.com/docs/commandline/fuse#healthcheck.path

**Comment by axelfontaine** [comment]
Full support for Spring Boot 2 has now been rolled out in the latest client release along with full autodetection of the new configuration property names and support for the new defaults.
