### ISSUE TITLE
Can't display all images for a given app (Gradle plugin)

### ISSUE THREAD

**Issue by pledbrook** [boxfuse/boxfuse-issues#35]
I can't work out how to get the same output from the `boxfuseLs` task as the `boxfuse ls` command. The former always seems to limit the images to the current project version.

**Comment by axelfontaine** [comment]
You are correct. Currently the filtering mechanism (also available for the regular command-line Boxfuse Client) kicks in automatically based on the info detected in build.gradle (project name & version).

Since gradle boxfuseLs will most likely be a manually invoked task, we could also disable the filtering altogether for gradle boxfuseLs & boxfusePs. Would that be a workable solution for you?

**Comment by pledbrook** [comment]
Workable, yes, but I'd prefer to have the filtering as an option. The current behaviour would be fine if it were possible to unset parts of the filter, for example app name and version. Perhaps by setting the corresponding property values to empty strings.

Such an approach would require independent properties for the `ps` and `ls` tasks, though, which would lead to too many Boxfuse properties. I think it would be better to expose the filtering options on the task itself, using the current behaviour as the default. Users could then bind the tasks' properties to their own project properties.

**Comment by axelfontaine** [comment]
This has now been fixed in the Boxfuse Gradle plugin v. 1.9.1.683

You can now unset the filters by setting boxfuse.app to an empty value. Example: ```gradle boxfuseLs -Dboxfuse.app=```

Updated docs at https://boxfuse.com/docs/gradle/, https://boxfuse.com/docs/gradle/ls.html and https://boxfuse.com/docs/gradle/ps.html to reflect this.

Cheers
Axel
