### ISSUE TITLE
Amazon Cloudwatch Logs

### ISSUE THREAD

**Issue by tomhughesnice** [boxfuse/boxfuse-issues#42]
Amazon provide a tool to monitor logs to detect errors and whatnot. This will be very useful to me so I can be sure my application is working properly.

This requires an agent to be running on your EC2 instance and looks fairly straightforward. https://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/QuickStartEC2Instance.html

Could you look into this or provide an alternate solution?

**Comment by axelfontaine** [comment]
What exactly are you trying to achieve? Is this just for sending application logs?

If that is the case, would something like this help: https://github.com/Bankmonitor/logback-appenders

What about Loggly, Logentries or Papertrail?

**Comment by tomhughesnice** [comment]
I want to keep everything wthin the Amazon ecosystem as much as possible,
so I wanted to try Cloudwatch before trying more familiar services like
Loggly.

Your github link provides the solution to this problem without having to
install an agent on your EC2 instance as Amazon suggests.

**Comment by forbode** [comment]
I accomplished this using a Cloudwatch Logback appender similar to Bank Monitor. This is something that doesn't need to be a part of Boxfuse.

**Comment by axelfontaine** [comment]
We have actually put quite a bit of thought into this over the last two months and really like the idea to add out of the box CloudWatch Logs support, including the ability to quickly view and correlate logs for all applications in a certain environment. We'll be detailing our plans soon and would love to hear your thoughts about them.

**Comment by jtheuer** [comment]
I'm usually a fan of putting as much logic as possible into the application since this is easier to customize and test. That is why we use slf4j + logback + logentries appender. This is great as long as "everything works" it however is not capable of capturing the hard crashes that go directly to STDERR, like OutOfMemoryError or JVM crashes. In this case it might be more clever to log to stdout and have a second process capturing stdout and stderr and forwarding it to whatever service you use.
Haven't seen any convincing solution, yet, so I'm curios about what you are going to build. I guess at the moment stdout/stderr would be visible in the console log which is at least available for a moment after instance termination.

**Comment by forbode** [comment]
I've since decided to convert my code to use the Boxfuse Cloudwatch feature (it's faster). However, I don't see documentation on how to convert existing applications to use this. Can someone point to it? 
So far I've seen this:

https://boxfuse.com/blog/cloudwatch-logs

**Comment by axelfontaine** [comment]
@forbode We have an open feature request for this: #117

Until this is implemented, feel free to send us the list of apps you want converted and we'll convert them for you.
