### ISSUE TITLE
Load balancer and security groups SSL issue

### ISSUE THREAD

**Issue by tomhughesnice** [boxfuse/boxfuse-issues#45]
I have setup my load balancer to accept SSL connections in order for this to connect to my boxfuse app I had to modify the associated security group to allow the inbound HTTPS on 443. Which worked fine.

The problem I have is that every time I redeploy my app the security group is recreated and the HTTPS mapping is lost. So I need to manually make this change again. Is there a way to facilitate this?

I have spent all day trying to get SSL to work on my boxfuse instance as per your instruction here. https://boxfuse.com/docs/payloads/springboot.html. The app starts up correctly and I can see that Tomcat is listening on port 443, but I can never get it to pass the health check.. Tbh though I dont think I really need this anyway, SSL connection to the load balancer only is good enough for me.

**Comment by axelfontaine** [comment]
I just check the logs for your account and saw this warning: ELB (boxlb-tomhughesnice-test-auth-ap) healthcheck is currently configured as TCP:80 but should be HTTPS:443/health for tomhughesnice/auth-api:0.0.0.1446215317466 => adjust in the AWS console to fix

This is something that happens when the ELB was first set up with different settings from the ones the application currents requires. You need to adjust this in the AWS console. We may provide a button in the Boxfuse Console in the future to be able to do this with one click from there.

The reason we don't do this automatically is that we can't change this without potentially causing the currently deployed version to be terminated and causing application downtime.

Does that work for you?

**Comment by tomhughesnice** [comment]
Ok will try another deployment now with those settings.

**Comment by tomhughesnice** [comment]
Is there a solution where I can just have an SSL certificate in my load balancer? I dont want to setup SSL in each Spring boot tomcat instance.
I have this currently setup a for https://auth-dev.fieldmargin.com/health.. But I need to add HTTP port 443 to the inbound security group each time I redeploy. I would like this setting to persist each deploy.

**Comment by axelfontaine** [comment]
Yes, you can have your own ELB (unmanaged by Boxfuse) setup, by
- killing the deployment in the environment you want to change
- create and configure an ELB as you need it
- configure your app in the Boxfuse Console or using the cfg command to use it (see: https://boxfuse.com/docs/commandline/cfg.html)

You can also do the same for the security group:
- create and configure a security group as you need it
- configure your app in the Boxfuse Console or using the cfg command to use it (see: https://boxfuse.com/docs/commandline/cfg.html)

However this probably won't be necessary. You can specify both an https and an http port in your app config. The healthcheck will then by default be performed on the https port. You can override this with the healthcheck.port setting.

If you don't mind me asking, what is the reason why you want the certificate on the ELB instead of the instance?

**Comment by tomhughesnice** [comment]
Thanks for the help i will try that out..

Simplicity is really the only reason at the moment. It was very easy to upload my CA SSL certificate chain to Amazon to be used on the load balancer. Having no luck configuring it Spring Boot as im not sure how to import an SSL certificate chain into a java keystore and get Spring boot to work with it. 

I have to release our software later this month, so dont really have the time to look at it presently.

**Comment by axelfontaine** [comment]
Fair enough. I found the trickiest part was converting whatever format you get from your CA into a Java keystore. The subsequent Spring Boot configuration is actually OK.

Some links to do this in case you do want to go down that path after all (we use it and it works well for us):
- http://stackoverflow.com/a/13992135/350428
- http://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-servlet-containers.html#howto-configure-ssl

**Comment by tomhughesnice** [comment]
Thanks for that, I have been trawling through stack overflow and found many articles never quite solving my problem. TBH though I doubt I will ever setup SSL in the boxfuse instance, I think the load balancer is good enough. As the client connection to the load balancer is the largest security threat for man in the middle attacks. If they managed to get between my load balancer and instance,,, well I think im well and truly hacked by that point anyway.

Those cfg commands worked fine. TBH I am going todo that to all my instances regardless.. I dont need a separate group for each instance when one can do the job.

**Comment by axelfontaine** [comment]
OK. Feel free to close this issue whenever you feel it has been resolved. If anything else comes up I'll be happy to help.

**Comment by axelfontaine** [comment]
I am closing this issue for now as I assume no news is good news. Feel free to reopen if necessary.
