### ISSUE TITLE
BackendConnectionErrors during blue-green deployment

### ISSUE THREAD

**Issue by jtheuer** [boxfuse/boxfuse-issues#71]
I checked the CloudWatch graph of my system during blue-green deployment (did two deployments, around 12:15 and 12:25) and noticed this:

![bildschirmfoto 2016-04-07 um 14 30 02](https://cloud.githubusercontent.com/assets/96364/14351058/6a77e338-fccd-11e5-944d-d044e3a82ded.png)

At the time of the deployment, BackendConnectionErrors occur. I checked the NewRelic graphs but nothing pops up there. I guess it must be between ELB and my application. Any ideas? Can I provide more information? (There are 2 ELB_5xx errors at the same time)

**Comment by axelfontaine** [comment]
As the AWS docs (http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/elb-cloudwatch-metrics.html) state: 

> Note that this count also includes any connection errors related to health checks.

This is therefore most likely due to the ELB failing to connect to the new version while it is starting up. Note that the instances are not in service yet at that time as they must first pass the ELB health checks to be put in service, hence the reason why New relic remains happy. This is purely an internal thing between ELB and new instances booting up, with no user-visible impact.

**Comment by jtheuer** [comment]
I'll futher monitor that.

I was just wondering why the value is so high (600 requests in one minute). This rather matches the RequestCount, than the health-check interval (every 2 seconds).

**Comment by axelfontaine** [comment]
Yes, please keep us posted if you discover anything out of the ordinary!
