### ISSUE TITLE
Feature request: allow upgrades from files.boxfuse.com to be served over https

### ISSUE THREAD

**Issue by HunterSherms** [boxfuse/boxfuse-issues#94]
Our firewalls block port 80, so we have to open access to files.boxfuse.com on each available upgrade. It would be great if we could reach this URL via https.

**Comment by boxfuse** [comment]
Actually all URLs are https, including files.boxfuse.com (albeit with SNI).
Are you seeing some kind of error with HTTPS?
On Jul 8, 2016 9:11 PM, "Hunter Sherman" <notifications@github.com> wrote:

Our firewalls block port 80, so we have to open access to files.boxfuse.com
on each available upgrade. It would be great if we could reach this URL via
https.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/boxfuse/boxfuse-issues/issues/94>, or mute the thread
<https://github.com/notifications/unsubscribe/AGak9j6UuibtwgmULzxS6I805gH3vLOyks5qTqDngaJpZM4JIUJi>
.

**Comment by axelfontaine** [comment]
Actually upon further investigation you were absolutely right. Sorry for the trouble and the confusion. We did indeed still deliver update URLs with http. This has now been fixed and all URLs are now truly HTTPS.
